2017-08-02T15:54:11.6470960+03:00 0HL6PKM982GKP [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (e5be5b71)
2017-08-02T15:54:11.8853020+03:00 0HL6PKM982GKP [ERR] An unhandled exception has occurred: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information. (fc7986d0)
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetControllerTypes()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.GetCollection()
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
2017-08-02T15:54:11.9219150+03:00 0HL6PKM982GKP [ERR] An exception was thrown attempting to execute the error handler. (e55ade05)
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetControllerTypes()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.GetCollection()
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
2017-08-02T15:54:11.9393570+03:00 0HL6PKM982GKP [ERR] Connection id ""0HL6PKM8U2PG8"": An unhandled exception was thrown by the application. (8c14976b)
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetControllerTypes()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.GetCollection()
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
2017-08-02T15:54:12.0966860+03:00 0HL6PKM982GKP [INF] Request finished in 542.9452ms 500  (15c52c40)
2017-08-02T15:54:18.4873120+03:00 0HL6PKM982GKQ [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (e5be5b71)
2017-08-02T15:54:18.5008090+03:00 0HL6PKM982GKQ [ERR] An unhandled exception has occurred: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information. (fc7986d0)
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetControllerTypes()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.GetCollection()
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
2017-08-02T15:54:18.5133980+03:00 0HL6PKM982GKQ [ERR] An exception was thrown attempting to execute the error handler. (e55ade05)
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetControllerTypes()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.GetCollection()
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
2017-08-02T15:54:18.5189380+03:00 0HL6PKM982GKQ [ERR] Connection id ""0HL6PKM8U2PG8"": An unhandled exception was thrown by the application. (8c14976b)
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetControllerTypes()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.GetCollection()
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
2017-08-02T15:54:18.5194580+03:00 0HL6PKM982GKQ [INF] Request finished in 32.1692ms 500  (15c52c40)
2017-08-02T15:55:43.6969450+03:00  [INF] webpack built 58c21f0dd06b3b8bb7f9 in 19862ms (d6203f13)
2017-08-02T15:57:19.4176130+03:00 0HL6PKO16GL0N [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (e5be5b71)
2017-08-02T15:57:19.5942960+03:00 0HL6PKO16GL0N [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetControllerTypes()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.GetCollection()
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2017-08-02T15:57:20.0938620+03:00 0HL6PKO16GL0N [INF] Request finished in 639.7917ms 500 text/html; charset=utf-8 (15c52c40)
2017-08-02T15:57:20.8504260+03:00 0HL6PKO16GL0O [INF] Request starting HTTP/1.1 GET http://localhost:5000/favicon.ico   (e5be5b71)
2017-08-02T15:57:20.8955610+03:00 0HL6PKO16GL0O [INF] Sending file. Request path: '"/favicon.ico"'. Physical path: '"/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/wwwroot/favicon.ico"' (27b0a520)
2017-08-02T15:57:20.9608160+03:00 0HL6PKO16GL0O [INF] Request finished in 110.4234ms 200 image/x-icon (15c52c40)
2017-08-02T15:57:53.2486080+03:00  [INF] Received SIGINT. Waiting for .NET process to exit... (39e2bf0e)
2017-08-02T16:00:01.4706660+03:00 0HL6PKPHG6V8L [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (e5be5b71)
2017-08-02T16:00:01.7529070+03:00 0HL6PKPHG6V8L [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetControllerTypes()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.GetCollection()
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2017-08-02T16:00:02.5224660+03:00 0HL6PKPHG6V8L [INF] Request finished in 1025.6682ms 500 text/html; charset=utf-8 (15c52c40)
2017-08-02T16:00:03.5535090+03:00 0HL6PKPHG6V8M [INF] Request starting HTTP/1.1 GET http://localhost:5000/favicon.ico   (e5be5b71)
2017-08-02T16:00:03.5946000+03:00 0HL6PKPHG6V8M [INF] Sending file. Request path: '"/favicon.ico"'. Physical path: '"/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/wwwroot/favicon.ico"' (27b0a520)
2017-08-02T16:00:03.6494680+03:00 0HL6PKPHG6V8M [INF] Request finished in 95.9517ms 200 image/x-icon (15c52c40)
2017-08-02T16:00:11.0861460+03:00  [INF] webpack built 58c21f0dd06b3b8bb7f9 in 18870ms (b0c4674f)
2017-08-02T16:00:18.6280380+03:00  [INF] Received SIGINT. Waiting for .NET process to exit... (39e2bf0e)
2017-08-02T16:04:27.7323090+03:00  [INF] webpack built 58c21f0dd06b3b8bb7f9 in 14793ms (25e5174c)
2017-08-02T16:04:33.6804200+03:00 0HL6PKS2JVHQL [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (e5be5b71)
2017-08-02T16:04:34.0528480+03:00 0HL6PKS2JVHQL [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetControllerTypes()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.GetCollection()
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2017-08-02T16:04:34.7036600+03:00 0HL6PKS2JVHQL [INF] Request finished in 983.9422ms 500 text/html; charset=utf-8 (15c52c40)
2017-08-02T16:04:35.3089710+03:00 0HL6PKS2JVHQM [INF] Request starting HTTP/1.1 GET http://localhost:5000/favicon.ico   (e5be5b71)
2017-08-02T16:04:35.3430180+03:00 0HL6PKS2JVHQM [INF] Sending file. Request path: '"/favicon.ico"'. Physical path: '"/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/wwwroot/favicon.ico"' (27b0a520)
2017-08-02T16:04:35.4070010+03:00 0HL6PKS2JVHQM [INF] Request finished in 98.0429ms 200 image/x-icon (15c52c40)
2017-08-02T16:05:21.9207940+03:00 0HL6PKS2JVHQN [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (e5be5b71)
2017-08-02T16:05:22.0414570+03:00 0HL6PKS2JVHQN [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetControllerTypes()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.GetCollection()
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2017-08-02T16:05:22.0926910+03:00 0HL6PKS2JVHQN [INF] Request finished in 169.9783ms 500 text/html; charset=utf-8 (15c52c40)
2017-08-02T16:05:23.1418700+03:00 0HL6PKS2JVHQO [INF] Request starting HTTP/1.1 GET http://localhost:5000/favicon.ico   (e5be5b71)
2017-08-02T16:05:23.1423390+03:00 0HL6PKS2JVHQO [INF] Sending file. Request path: '"/favicon.ico"'. Physical path: '"/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/wwwroot/favicon.ico"' (27b0a520)
2017-08-02T16:05:23.1436350+03:00 0HL6PKS2JVHQO [INF] Request finished in 1.7913ms 200 image/x-icon (15c52c40)
2017-08-02T16:07:05.3343580+03:00  [INF] Received SIGINT. Waiting for .NET process to exit... (39e2bf0e)
2017-08-02T16:24:51.3146970+03:00 0HL6PL7DGAMI7 [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (e5be5b71)
2017-08-02T16:24:52.0951190+03:00 0HL6PL7DGAMI7 [INF] Executing action method "NXS.Controllers.HomeController.Index (NXS)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-02T16:24:56.0100790+03:00 0HL6PL7DGAMI7 [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2017-08-02T16:24:56.2072480+03:00 0HL6PL7DGAMI7 [INF] User profile is available. Using '"/Users/andriyarysmyatov/.aspnet/DataProtection-Keys"' as key repository; keys will not be encrypted at rest. (a162847e)
2017-08-02T16:24:58.1798780+03:00 0HL6PL7DGAMI7 [INF] Node will restart because file changed: /Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/main-server.js (23d2f42c)
2017-08-02T16:24:58.6315170+03:00 0HL6PL7DGAMI7 [ERR] ERROR Error: jQuery requires a window with a document
    at module.exports.module.exports (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:19055:12)
    at HeaderComponent.ngAfterViewInit (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/main-server.js:13654:9)
    at callProviderLifecycles (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:15689:18)
    at callElementProvidersLifecycles (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:15664:13)
    at callLifecycleHooksChildrenFirst (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:15648:17)
    at checkAndUpdateView (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:16680:5)
    at callViewAction (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:17035:21)
    at execComponentViewsAction (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:16967:13)
    at Object.checkAndUpdateView (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:16678:5)
    at ViewRef_.module.exports.ViewRef_.detectChanges (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:14746:63) (34058d77)
2017-08-02T16:24:59.4767310+03:00 0HL6PL7DGAMI8 [INF] Request starting HTTP/1.1 GET http://localhost:5000/dist/vendor.css?v=6V1XE9pBNVWZaG1AlsRZYfHMbu0miv3EsiQv-8jKmIg   (e5be5b71)
2017-08-02T16:24:59.6844480+03:00 0HL6PL7DGAMI7 [INF] Executed action "NXS.Controllers.HomeController.Index (NXS)" in 7692.7993ms (afa2e885)
2017-08-02T16:24:59.8103980+03:00 0HL6PL7DGAMI7 [INF] Request finished in 8561.866ms 200 text/html; charset=utf-8 (15c52c40)
2017-08-02T16:24:59.8355830+03:00 0HL6PL7DGAMI9 [INF] Request starting HTTP/1.1 GET http://localhost:5000/dist/vendor.js?v=biT_xtz2y6Dm90XA962AZhAQ5b10hg1nNv_lMfkSrzQ   (e5be5b71)
2017-08-02T16:24:59.8443150+03:00 0HL6PL7DGAMIA [INF] Request starting HTTP/1.1 GET http://localhost:5000/dist/main-client.js?v=gs9CuABfQKCtL-Q4LPfoQ4hbv3Rsz6MGH7oOziAIsAI   (e5be5b71)
2017-08-02T16:25:00.5666660+03:00  [INF] webpack built 58c21f0dd06b3b8bb7f9 in 16697ms (f6edb882)
2017-08-02T16:25:00.6466510+03:00 0HL6PL7DGAMIA [INF] Request finished in 802.0328ms 200 application/javascript; charset=UTF-8 (15c52c40)
2017-08-02T16:25:00.6897140+03:00 0HL6PL7DGAMI9 [INF] Sending file. Request path: '"/dist/vendor.js"'. Physical path: '"/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/wwwroot/dist/vendor.js"' (27b0a520)
2017-08-02T16:25:00.6898670+03:00 0HL6PL7DGAMI8 [INF] Sending file. Request path: '"/dist/vendor.css"'. Physical path: '"/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/wwwroot/dist/vendor.css"' (27b0a520)
2017-08-02T16:25:00.7369110+03:00 0HL6PL7DGAMI8 [INF] Request finished in 1259.1617ms 200 text/css (15c52c40)
2017-08-02T16:25:01.4890880+03:00 0HL6PL7DGAMI9 [INF] Request finished in 1653.651ms 200 application/javascript (15c52c40)
2017-08-02T16:25:03.5078770+03:00 0HL6PL7DGAMIB [INF] Request starting HTTP/1.1 GET http://localhost:5000/dist/6ebdb1f01dc905110782925239a570f8.jpg   (e5be5b71)
2017-08-02T16:25:03.5269310+03:00 0HL6PL7DGAMIB [INF] Request finished in 19.066ms 200 image/jpeg; charset=UTF-8 (15c52c40)
2017-08-02T16:25:03.5918600+03:00 0HL6PL7DGAMIC [INF] Request starting HTTP/1.1 GET http://localhost:5000/__webpack_hmr   (e5be5b71)
2017-08-02T16:31:47.4453320+03:00 0HL6PLB9GT51J [INF] Request starting HTTP/1.1 GET http://localhost:5000/__webpack_hmr   (e5be5b71)
2017-08-02T16:31:57.6233840+03:00  [INF] webpack built 58c21f0dd06b3b8bb7f9 in 11960ms (1f490a4f)
2017-08-02T16:33:02.2093670+03:00 0HL6PLB9GT51K [INF] Request starting HTTP/1.1 POST http://localhost:5000/api/account multipart/form-data; boundary=----WebKitFormBoundaryyW4oBcCIDosvdyBR 469 (e5be5b71)
2017-08-02T16:33:03.0434860+03:00 0HL6PLB9GT51K [INF] Executing HttpStatusCodeResult, setting HTTP status code 415 (e28ccfae)
2017-08-02T16:33:03.0690110+03:00 0HL6PLB9GT51K [INF] Executed action "NXS.Controllers.AccountController.Post (NXS)" in 431.0823ms (afa2e885)
2017-08-02T16:33:03.1037250+03:00 0HL6PLB9GT51K [INF] Request finished in 885.4732ms 415  (15c52c40)
2017-08-02T16:35:29.9842800+03:00 0HL6PLB9GT51L [INF] Request starting HTTP/1.1 POST http://localhost:5000/api/account application/json 128 (e5be5b71)
2017-08-02T16:35:30.0849030+03:00 0HL6PLB9GT51L [INF] Executing action method "NXS.Controllers.AccountController.Post (NXS)" with arguments ([""]) - ModelState is Invalid (ba7f4ac2)
2017-08-02T16:35:30.1413550+03:00 0HL6PLB9GT51L [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2017-08-02T16:35:30.1835970+03:00 0HL6PLB9GT51L [INF] Executed action "NXS.Controllers.AccountController.Post (NXS)" in 195.0412ms (afa2e885)
2017-08-02T16:35:30.1880220+03:00 0HL6PLB9GT51L [INF] Request finished in 203.9682ms 400 application/json; charset=utf-8 (15c52c40)
2017-08-02T16:35:58.9518650+03:00 0HL6PLB9GT51M [INF] Request starting HTTP/1.1 POST http://localhost:5000/api/account application/json 120 (e5be5b71)
2017-08-02T16:35:58.9534570+03:00 0HL6PLB9GT51M [INF] Executing action method "NXS.Controllers.AccountController.Post (NXS)" with arguments ([""]) - ModelState is Invalid (ba7f4ac2)
2017-08-02T16:35:58.9539330+03:00 0HL6PLB9GT51M [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2017-08-02T16:35:58.9541840+03:00 0HL6PLB9GT51M [INF] Executed action "NXS.Controllers.AccountController.Post (NXS)" in 2.0329ms (afa2e885)
2017-08-02T16:35:58.9542780+03:00 0HL6PLB9GT51M [INF] Request finished in 2.4896ms 400 application/json; charset=utf-8 (15c52c40)
2017-08-02T16:36:11.2900150+03:00 0HL6PLB9GT51N [INF] Request starting HTTP/1.1 POST http://localhost:5000/api/account application/json 120 (e5be5b71)
2017-08-02T16:36:11.3692970+03:00 0HL6PLB9GT51N [INF] Executing action method "NXS.Controllers.AccountController.Post (NXS)" with arguments (["NXS.Controllers.Resources.RegistrationInfoResource"]) - ModelState is Valid (ba7f4ac2)
2017-08-02T16:36:11.4245200+03:00 0HL6PLB9GT51N [INF] Executed action "NXS.Controllers.AccountController.Post (NXS)" in 134.2048ms (afa2e885)
2017-08-02T16:36:11.5095470+03:00 0HL6PLB9GT51N [ERR] An unhandled exception has occurred while executing the request (cf926119)
AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping.

Mapping types:
RegistrationInfoResource -> NxsUser
NXS.Controllers.Resources.RegistrationInfoResource -> NXS.Core.Models.NxsUser
   at lambda_method(Closure , Object , Object , ResolutionContext )
   at AutoMapper.Mapper.AutoMapper.IMapper.Map[TDestination](Object source)
   at NXS.Controllers.AccountController.<Post>d__4.MoveNext() in /Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/Controllers/AccountController.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2017-08-02T16:36:11.6590390+03:00 0HL6PLB9GT51N [INF] Request finished in 368.9906ms 500 text/html; charset=utf-8 (15c52c40)
2017-08-02T16:36:25.3164430+03:00  [INF] Received SIGINT. Waiting for .NET process to exit... (39e2bf0e)
2017-08-02T16:37:01.5052950+03:00 0HL6PLE73VQ6T [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (e5be5b71)
2017-08-02T16:37:02.7784970+03:00 0HL6PLE73VQ6T [INF] Executing action method "NXS.Controllers.HomeController.Index (NXS)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-02T16:37:08.1481730+03:00 0HL6PLE73VQ6U [INF] Request starting HTTP/1.1 POST http://localhost:5000/api/account application/json 120 (e5be5b71)
2017-08-02T16:37:09.0287680+03:00 0HL6PLE73VQ6U [INF] Executing action method "NXS.Controllers.AccountController.Post (NXS)" with arguments (["NXS.Controllers.Resources.RegistrationInfoResource"]) - ModelState is Valid (ba7f4ac2)
2017-08-02T16:37:19.4576380+03:00  [INF] webpack built 58c21f0dd06b3b8bb7f9 in 19419ms (1bb7f1ee)
2017-08-02T16:37:20.3938880+03:00 0HL6PLE73VQ6U [INF] Executed action "NXS.Controllers.AccountController.Post (NXS)" in 12186.9834ms (afa2e885)
2017-08-02T16:37:20.7140200+03:00 0HL6PLE73VQ6U [ERR] An unhandled exception has occurred while executing the request (cf926119)
AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping.

Mapping types:
RegistrationInfoResource -> NxsUser
NXS.Controllers.Resources.RegistrationInfoResource -> NXS.Core.Models.NxsUser
   at lambda_method(Closure , Object , Object , ResolutionContext )
   at AutoMapper.Mapper.AutoMapper.IMapper.Map[TDestination](Object source)
   at NXS.Controllers.AccountController.<Post>d__4.MoveNext() in /Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/Controllers/AccountController.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2017-08-02T16:37:21.2754690+03:00 0HL6PLE73VQ6U [INF] Request finished in 13108.4132ms 500 text/html; charset=utf-8 (15c52c40)
2017-08-02T16:37:22.6454120+03:00 0HL6PLE73VQ6T [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2017-08-02T16:37:22.8523630+03:00 0HL6PLE73VQ6T [INF] User profile is available. Using '"/Users/andriyarysmyatov/.aspnet/DataProtection-Keys"' as key repository; keys will not be encrypted at rest. (a162847e)
2017-08-02T16:37:25.4194560+03:00 0HL6PLE73VQ6T [ERR] ERROR Error: jQuery requires a window with a document
    at module.exports.module.exports (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:19055:12)
    at HeaderComponent.ngAfterViewInit (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/main-server.js:13654:9)
    at callProviderLifecycles (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:15689:18)
    at callElementProvidersLifecycles (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:15664:13)
    at callLifecycleHooksChildrenFirst (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:15648:17)
    at checkAndUpdateView (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:16680:5)
    at callViewAction (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:17035:21)
    at execComponentViewsAction (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:16967:13)
    at Object.checkAndUpdateView (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:16678:5)
    at ViewRef_.module.exports.ViewRef_.detectChanges (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:14746:63) (34058d77)
2017-08-02T16:37:26.2124250+03:00  [INF] Connection id ""0HL6PLE6MTB4I"" communication error. (7fa6c29c)
Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -32 EPIPE broken pipe
2017-08-02T16:37:26.2226680+03:00 0HL6PLE73VQ6T [INF] Executed action "NXS.Controllers.HomeController.Index (NXS)" in 23618.7438ms (afa2e885)
2017-08-02T16:37:26.2310970+03:00 0HL6PLE73VQ6T [INF] Request finished in 24957.1794ms 200 text/html; charset=utf-8 (15c52c40)
2017-08-02T16:48:42.9338660+03:00 0HL6PLKO59V07 [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (e5be5b71)
2017-08-02T16:48:44.3092090+03:00 0HL6PLKO59V07 [INF] Executing action method "NXS.Controllers.HomeController.Index (NXS)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-02T16:48:52.2091870+03:00 0HL6PLKO59V08 [INF] Request starting HTTP/1.1 POST http://localhost:5000/api/account application/json 120 (e5be5b71)
2017-08-02T16:48:53.3835030+03:00 0HL6PLKO59V08 [INF] Executing action method "NXS.Controllers.AccountController.Post (NXS)" with arguments (["NXS.Controllers.Resources.RegistrationInfoResource"]) - ModelState is Valid (ba7f4ac2)
2017-08-02T16:49:02.1574080+03:00 0HL6PLKO59V08 [INF] Executed action "NXS.Controllers.AccountController.Post (NXS)" in 9888.1498ms (afa2e885)
2017-08-02T16:49:02.3877360+03:00 0HL6PLKO59V08 [ERR] An unhandled exception has occurred while executing the request (cf926119)
AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping.

Mapping types:
RegistrationInfoResource -> NxsUser
NXS.Controllers.Resources.RegistrationInfoResource -> NXS.Core.Models.NxsUser
   at lambda_method(Closure , Object , Object , ResolutionContext )
   at AutoMapper.Mapper.AutoMapper.IMapper.Map[TDestination](Object source)
   at NXS.Controllers.AccountController.<Post>d__4.MoveNext() in /Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/Controllers/AccountController.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2017-08-02T16:49:03.2975860+03:00 0HL6PLKO59V07 [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2017-08-02T16:49:03.3437620+03:00 0HL6PLKO59V08 [INF] Request finished in 11078.3752ms 500 text/html; charset=utf-8 (15c52c40)
2017-08-02T16:49:03.6883080+03:00 0HL6PLKO59V07 [INF] User profile is available. Using '"/Users/andriyarysmyatov/.aspnet/DataProtection-Keys"' as key repository; keys will not be encrypted at rest. (a162847e)
2017-08-02T16:49:04.1858120+03:00 0HL6PLKO59V07 [INF] Node will restart because file changed: /Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/main-server.js (23d2f42c)
2017-08-02T16:49:07.0640330+03:00  [INF] webpack built 58c21f0dd06b3b8bb7f9 in 26670ms (7c179536)
2017-08-02T16:49:07.5356600+03:00 0HL6PLKO59V07 [ERR] ERROR Error: jQuery requires a window with a document
    at module.exports.module.exports (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:19055:12)
    at HeaderComponent.ngAfterViewInit (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/main-server.js:13654:9)
    at callProviderLifecycles (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:15689:18)
    at callElementProvidersLifecycles (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:15664:13)
    at callLifecycleHooksChildrenFirst (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:15648:17)
    at checkAndUpdateView (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:16680:5)
    at callViewAction (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:17035:21)
    at execComponentViewsAction (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:16967:13)
    at Object.checkAndUpdateView (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:16678:5)
    at ViewRef_.module.exports.ViewRef_.detectChanges (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:14746:63) (34058d77)
2017-08-02T16:49:08.4607930+03:00 0HL6PLKO59V09 [INF] Request starting HTTP/1.1 GET http://localhost:5000/dist/vendor.js?v=biT_xtz2y6Dm90XA962AZhAQ5b10hg1nNv_lMfkSrzQ   (e5be5b71)
2017-08-02T16:49:08.4993120+03:00 0HL6PLKO59V0A [INF] Request starting HTTP/1.1 GET http://localhost:5000/dist/vendor.css?v=6V1XE9pBNVWZaG1AlsRZYfHMbu0miv3EsiQv-8jKmIg   (e5be5b71)
2017-08-02T16:49:08.5237400+03:00 0HL6PLKO59V0B [INF] Request starting HTTP/1.1 GET http://localhost:5000/dist/main-client.js?v=gs9CuABfQKCtL-Q4LPfoQ4hbv3Rsz6MGH7oOziAIsAI   (e5be5b71)
2017-08-02T16:49:08.6025640+03:00 0HL6PLKO59V07 [INF] Executed action "NXS.Controllers.HomeController.Index (NXS)" in 24525.6982ms (afa2e885)
2017-08-02T16:49:08.9758410+03:00 0HL6PLKO59V07 [INF] Request finished in 26179.329ms 200 text/html; charset=utf-8 (15c52c40)
2017-08-02T16:49:09.1759100+03:00 0HL6PLKO59V0A [INF] The file "/dist/vendor.css" was not modified (f1f8d725)
2017-08-02T16:49:09.1892980+03:00 0HL6PLKO59V09 [INF] The file "/dist/vendor.js" was not modified (f1f8d725)
2017-08-02T16:49:09.2073870+03:00 0HL6PLKO59V0A [INF] Request finished in 708.0773ms 304 text/css (15c52c40)
2017-08-02T16:49:09.2073870+03:00 0HL6PLKO59V09 [INF] Request finished in 746.5276ms 304 application/javascript (15c52c40)
2017-08-02T16:49:09.4186640+03:00 0HL6PLKO59V0B [INF] Request finished in 894.9408ms 200 application/javascript; charset=UTF-8 (15c52c40)
2017-08-02T16:49:11.5063000+03:00 0HL6PLKO59V0C [INF] Request starting HTTP/1.1 GET http://localhost:5000/__webpack_hmr   (e5be5b71)
2017-08-02T16:49:11.6255860+03:00 0HL6PLKO59V0D [INF] Request starting HTTP/1.1 GET http://localhost:5000/dist/6ebdb1f01dc905110782925239a570f8.jpg   (e5be5b71)
2017-08-02T16:49:11.8046670+03:00 0HL6PLKO59V0D [INF] Request finished in 228.1487ms 200 image/jpeg; charset=UTF-8 (15c52c40)
2017-08-02T16:50:42.9623350+03:00 0HL6PLLRU0PDH [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (e5be5b71)
2017-08-02T16:50:44.0678480+03:00 0HL6PLLRU0PDH [INF] Executing action method "NXS.Controllers.HomeController.Index (NXS)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-02T16:50:49.4970590+03:00 0HL6PLLRU0PDI [INF] Request starting HTTP/1.1 POST http://localhost:5000/api/account application/json 120 (e5be5b71)
2017-08-02T16:50:50.4690360+03:00 0HL6PLLRU0PDI [INF] Executing action method "NXS.Controllers.AccountController.Post (NXS)" with arguments (["NXS.Controllers.Resources.RegistrationInfoResource"]) - ModelState is Valid (ba7f4ac2)
2017-08-02T16:51:22.6907630+03:00  [INF] webpack built 58c21f0dd06b3b8bb7f9 in 18917ms (42dec4f7)
2017-08-02T16:51:23.0638160+03:00 0HL6PLLRU0PDI [INF] Executed action "NXS.Controllers.AccountController.Post (NXS)" in 33484.4076ms (afa2e885)
2017-08-02T16:51:23.2826650+03:00 0HL6PLLRU0PDI [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.NullReferenceException: Object reference not set to an instance of an object.
   at NXS.Controllers.AccountController.<Post>d__4.MoveNext() in /Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/Controllers/AccountController.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2017-08-02T16:51:23.7703130+03:00 0HL6PLLRU0PDI [INF] Request finished in 34259.8869ms 500 text/html; charset=utf-8 (15c52c40)
2017-08-02T16:51:24.0152150+03:00 0HL6PLLRU0PDH [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2017-08-02T16:51:24.2341530+03:00 0HL6PLLRU0PDH [INF] User profile is available. Using '"/Users/andriyarysmyatov/.aspnet/DataProtection-Keys"' as key repository; keys will not be encrypted at rest. (a162847e)
2017-08-02T16:51:26.1746730+03:00 0HL6PLLRU0PDH [ERR] ERROR Error: jQuery requires a window with a document
    at module.exports.module.exports (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:19055:12)
    at HeaderComponent.ngAfterViewInit (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/main-server.js:13654:9)
    at callProviderLifecycles (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:15689:18)
    at callElementProvidersLifecycles (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:15664:13)
    at callLifecycleHooksChildrenFirst (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:15648:17)
    at checkAndUpdateView (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:16680:5)
    at callViewAction (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:17035:21)
    at execComponentViewsAction (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:16967:13)
    at Object.checkAndUpdateView (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:16678:5)
    at ViewRef_.module.exports.ViewRef_.detectChanges (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:14746:63) (34058d77)
2017-08-02T16:51:26.8744450+03:00 0HL6PLLRU0PDH [INF] Executed action "NXS.Controllers.HomeController.Index (NXS)" in 42969.5206ms (afa2e885)
2017-08-02T16:51:26.9127290+03:00 0HL6PLLRU0PDJ [INF] Request starting HTTP/1.1 GET http://localhost:5000/dist/main-client.js?v=gs9CuABfQKCtL-Q4LPfoQ4hbv3Rsz6MGH7oOziAIsAI   (e5be5b71)
2017-08-02T16:51:26.9226910+03:00 0HL6PLLRU0PDH [INF] Request finished in 44098.5902ms 200 text/html; charset=utf-8 (15c52c40)
2017-08-02T16:51:27.2480690+03:00 0HL6PLLRU0PDJ [INF] Request finished in 335.3894ms 200 application/javascript; charset=UTF-8 (15c52c40)
2017-08-02T16:51:29.1525480+03:00 0HL6PLLRU0PDK [INF] Request starting HTTP/1.1 GET http://localhost:5000/dist/6ebdb1f01dc905110782925239a570f8.jpg   (e5be5b71)
2017-08-02T16:51:29.2070090+03:00 0HL6PLLRU0PDL [INF] Request starting HTTP/1.1 GET http://localhost:5000/__webpack_hmr   (e5be5b71)
2017-08-02T16:51:29.4683940+03:00 0HL6PLLRU0PDK [INF] Request finished in 315.7556ms 200 image/jpeg; charset=UTF-8 (15c52c40)
2017-08-02T16:53:33.5598960+03:00 0HL6PLLRU0PDM [INF] Request starting HTTP/1.1 POST http://localhost:5000/api/account application/json 120 (e5be5b71)
2017-08-02T16:53:33.5963770+03:00 0HL6PLLRU0PDM [INF] Executing action method "NXS.Controllers.AccountController.Post (NXS)" with arguments (["NXS.Controllers.Resources.RegistrationInfoResource"]) - ModelState is Valid (ba7f4ac2)
2017-08-02T16:56:08.0495140+03:00 0HL6PLLRU0PDN [INF] Request starting HTTP/1.1 GET http://localhost:5000/__webpack_hmr   (e5be5b71)
2017-08-02T16:56:08.8828850+03:00 0HL6PLLRU0PDM [INF] Executed action "NXS.Controllers.AccountController.Post (NXS)" in 155298.8288ms (afa2e885)
2017-08-02T16:56:08.9691650+03:00 0HL6PLLRU0PDM [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.NullReferenceException: Object reference not set to an instance of an object.
   at NXS.Controllers.AccountController.<Post>d__4.MoveNext() in /Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/Controllers/AccountController.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2017-08-02T16:56:08.9940820+03:00  [INF] Connection id ""0HL6PLLRK27S3"" communication error. (7fa6c29c)
Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -32 EPIPE broken pipe
2017-08-02T16:56:09.0718890+03:00 0HL6PLLRU0PDL [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.IO.Stream.<CopyToAsyncInternal>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<PerformProxyRequest>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2017-08-02T16:56:09.1532560+03:00 0HL6PLLRU0PDL [WRN] The response has already started, the error page middleware will not be executed. (e1dd4c0d)
2017-08-02T16:56:09.2021420+03:00 0HL6PLLRU0PDL [ERR] Connection id ""0HL6PLLRK27S3"": An unhandled exception was thrown by the application. (8c14976b)
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.IO.Stream.<CopyToAsyncInternal>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<PerformProxyRequest>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
2017-08-02T16:56:09.2420860+03:00 0HL6PLLRU0PDL [INF] Request finished in 280022.7662ms 200 text/event-stream; charset=utf-8 (15c52c40)
2017-08-02T16:56:09.2742790+03:00 0HL6PLLRU0PDM [INF] Request finished in 155708.7342ms 500 text/html; charset=utf-8 (15c52c40)
2017-08-02T17:01:12.1373630+03:00 0HL6PLRNEAGQR [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (e5be5b71)
2017-08-02T17:01:13.2243780+03:00 0HL6PLRNEAGQR [INF] Executing action method "NXS.Controllers.HomeController.Index (NXS)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-02T17:01:19.0354780+03:00 0HL6PLRNEAGQR [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2017-08-02T17:01:19.3433870+03:00 0HL6PLRNEAGQR [INF] User profile is available. Using '"/Users/andriyarysmyatov/.aspnet/DataProtection-Keys"' as key repository; keys will not be encrypted at rest. (a162847e)
2017-08-02T17:01:22.4998840+03:00 0HL6PLRNEAGQR [ERR] ERROR Error: jQuery requires a window with a document
    at module.exports.module.exports (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:19055:12)
    at HeaderComponent.ngAfterViewInit (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/main-server.js:13654:9)
    at callProviderLifecycles (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:15689:18)
    at callElementProvidersLifecycles (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:15664:13)
    at callLifecycleHooksChildrenFirst (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:15648:17)
    at checkAndUpdateView (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:16680:5)
    at callViewAction (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:17035:21)
    at execComponentViewsAction (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:16967:13)
    at Object.checkAndUpdateView (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:16678:5)
    at ViewRef_.module.exports.ViewRef_.detectChanges (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:14746:63) (34058d77)
2017-08-02T17:01:23.8163290+03:00 0HL6PLRNEAGQS [INF] Request starting HTTP/1.1 GET http://localhost:5000/dist/vendor.css?v=6V1XE9pBNVWZaG1AlsRZYfHMbu0miv3EsiQv-8jKmIg   (e5be5b71)
2017-08-02T17:01:23.8456990+03:00 0HL6PLRNEAGQR [INF] Executed action "NXS.Controllers.HomeController.Index (NXS)" in 10778.9796ms (afa2e885)
2017-08-02T17:01:24.0835060+03:00 0HL6PLRNEAGQT [INF] Request starting HTTP/1.1 GET http://localhost:5000/dist/vendor.js?v=biT_xtz2y6Dm90XA962AZhAQ5b10hg1nNv_lMfkSrzQ   (e5be5b71)
2017-08-02T17:01:24.2390860+03:00 0HL6PLRNEAGQU [INF] Request starting HTTP/1.1 GET http://localhost:5000/dist/main-client.js?v=gs9CuABfQKCtL-Q4LPfoQ4hbv3Rsz6MGH7oOziAIsAI   (e5be5b71)
2017-08-02T17:01:24.3992750+03:00 0HL6PLRNEAGQR [INF] Request finished in 12324.899ms 200 text/html; charset=utf-8 (15c52c40)
2017-08-02T17:01:29.9411710+03:00 0HL6PLRNEAGQV [INF] Node will restart because file changed: /Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/main-server.js (23d2f42c)
2017-08-02T17:01:30.3764470+03:00 0HL6PLRNEAGQV [INF] Request starting HTTP/1.1 GET http://localhost:5000/__webpack_hmr   (e5be5b71)
2017-08-02T17:01:34.2797650+03:00  [INF] webpack built 58c21f0dd06b3b8bb7f9 in 23916ms (295c278c)
2017-08-02T17:01:35.2646210+03:00 0HL6PLRNEAGQS [INF] The file "/dist/vendor.css" was not modified (f1f8d725)
2017-08-02T17:01:35.2734890+03:00 0HL6PLRNEAGQT [INF] The file "/dist/vendor.js" was not modified (f1f8d725)
2017-08-02T17:01:35.3178080+03:00 0HL6PLRNEAGQT [INF] Request finished in 11233.7758ms 304 application/javascript (15c52c40)
2017-08-02T17:01:35.3177930+03:00 0HL6PLRNEAGQS [INF] Request finished in 11501.1305ms 304 text/css (15c52c40)
2017-08-02T17:01:36.1079420+03:00 0HL6PLRNEAGQU [INF] Request finished in 11844.4975ms 200 application/javascript; charset=UTF-8 (15c52c40)
2017-08-02T17:01:40.9506140+03:00 0HL6PLRNEAGR0 [INF] Request starting HTTP/1.1 GET http://localhost:5000/__webpack_hmr   (e5be5b71)
2017-08-02T17:01:41.0466900+03:00 0HL6PLRNEAGR1 [INF] Request starting HTTP/1.1 GET http://localhost:5000/dist/6ebdb1f01dc905110782925239a570f8.jpg   (e5be5b71)
2017-08-02T17:01:41.6978450+03:00 0HL6PLRNEAGR1 [INF] Request finished in 650.9585ms 200 image/jpeg; charset=UTF-8 (15c52c40)
2017-08-02T17:01:51.7144540+03:00 0HL6PLRNEAGR2 [INF] Request starting HTTP/1.1 POST http://localhost:5000/api/account application/json 120 (e5be5b71)
2017-08-02T17:01:52.5492330+03:00 0HL6PLRNEAGR2 [INF] Executing action method "NXS.Controllers.AccountController.Post (NXS)" with arguments (["NXS.Controllers.Resources.RegistrationInfoResource"]) - ModelState is Valid (ba7f4ac2)
2017-08-02T17:01:59.6011310+03:00 0HL6PLRNEAGR2 [INF] Executed action "NXS.Controllers.AccountController.Post (NXS)" in 7780.8685ms (afa2e885)
2017-08-02T17:01:59.8346370+03:00 0HL6PLRNEAGR2 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.NullReferenceException: Object reference not set to an instance of an object.
   at NXS.Controllers.AccountController.<Post>d__4.MoveNext() in /Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/Controllers/AccountController.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2017-08-02T17:02:00.0955050+03:00 0HL6PLRNEAGR2 [INF] Request finished in 8387.1063ms 500 text/html; charset=utf-8 (15c52c40)
2017-08-02T17:02:18.3361320+03:00 0HL6PLRNEAGR3 [INF] Request starting HTTP/1.1 POST http://localhost:5000/api/account application/json 120 (e5be5b71)
2017-08-02T17:02:18.3602540+03:00 0HL6PLRNEAGR3 [INF] Executing action method "NXS.Controllers.AccountController.Post (NXS)" with arguments (["NXS.Controllers.Resources.RegistrationInfoResource"]) - ModelState is Valid (ba7f4ac2)
2017-08-02T17:04:01.4305300+03:00 0HL6PLT9ST49D [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (e5be5b71)
2017-08-02T17:04:02.8592900+03:00 0HL6PLT9ST49D [INF] Executing action method "NXS.Controllers.HomeController.Index (NXS)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-02T17:04:10.4055440+03:00 0HL6PLT9ST49D [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2017-08-02T17:04:10.7797830+03:00 0HL6PLT9ST49D [INF] User profile is available. Using '"/Users/andriyarysmyatov/.aspnet/DataProtection-Keys"' as key repository; keys will not be encrypted at rest. (a162847e)
2017-08-02T17:04:13.2735310+03:00 0HL6PLT9ST49E [INF] Request starting HTTP/1.1 GET http://localhost:5000/__webpack_hmr   (e5be5b71)
2017-08-02T17:04:13.4465600+03:00 0HL6PLT9ST49F [INF] Request starting HTTP/1.1 GET http://localhost:5000/__webpack_hmr   (e5be5b71)
2017-08-02T17:04:13.8053640+03:00 0HL6PLT9ST49D [ERR] ERROR Error: jQuery requires a window with a document
    at module.exports.module.exports (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:19055:12)
    at HeaderComponent.ngAfterViewInit (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/main-server.js:13654:9)
    at callProviderLifecycles (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:15689:18)
    at callElementProvidersLifecycles (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:15664:13)
    at callLifecycleHooksChildrenFirst (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:15648:17)
    at checkAndUpdateView (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:16680:5)
    at callViewAction (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:17035:21)
    at execComponentViewsAction (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:16967:13)
    at Object.checkAndUpdateView (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:16678:5)
    at ViewRef_.module.exports.ViewRef_.detectChanges (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:14746:63) (34058d77)
2017-08-02T17:04:14.9432070+03:00 0HL6PLT9ST49D [INF] Executed action "NXS.Controllers.HomeController.Index (NXS)" in 12291.8204ms (afa2e885)
2017-08-02T17:04:15.0202330+03:00 0HL6PLT9ST49D [INF] Request finished in 13731.4691ms 200 text/html; charset=utf-8 (15c52c40)
2017-08-02T17:04:15.3572210+03:00 0HL6PLT9ST49G [INF] Request starting HTTP/1.1 GET http://localhost:5000/dist/main-client.js?v=gs9CuABfQKCtL-Q4LPfoQ4hbv3Rsz6MGH7oOziAIsAI   (e5be5b71)
2017-08-02T17:04:17.4579620+03:00 0HL6PLT9ST49G [INF] Node will restart because file changed: /Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/main-server.js (23d2f42c)
2017-08-02T17:04:19.0941100+03:00  [INF] webpack built 58c21f0dd06b3b8bb7f9 in 19526ms (031c2464)
2017-08-02T17:04:19.3580460+03:00 0HL6PLT9ST49G [INF] Request finished in 4000.6177ms 200 application/javascript; charset=UTF-8 (15c52c40)
2017-08-02T17:04:21.4016980+03:00 0HL6PLT9ST49H [INF] Request starting HTTP/1.1 GET http://localhost:5000/dist/6ebdb1f01dc905110782925239a570f8.jpg   (e5be5b71)
2017-08-02T17:04:21.4184010+03:00 0HL6PLT9ST49I [INF] Request starting HTTP/1.1 GET http://localhost:5000/__webpack_hmr   (e5be5b71)
2017-08-02T17:04:21.7461680+03:00 0HL6PLT9ST49H [INF] Request finished in 344.6587ms 200 image/jpeg; charset=UTF-8 (15c52c40)
2017-08-02T17:07:37.6472130+03:00 0HL6PLT9ST49J [INF] Request starting HTTP/1.1 POST http://localhost:5000/api/account application/json 120 (e5be5b71)
2017-08-02T17:07:38.7168900+03:00 0HL6PLT9ST49J [INF] Executing action method "NXS.Controllers.AccountController.Post (NXS)" with arguments (["NXS.Controllers.Resources.RegistrationInfoResource"]) - ModelState is Valid (ba7f4ac2)
2017-08-02T17:07:52.6883040+03:00  [INF] Connection id ""0HL6PLT9JTA6C"" communication error. (7fa6c29c)
Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -32 EPIPE broken pipe
2017-08-02T17:07:53.0179640+03:00 0HL6PLT9ST49I [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.IO.Stream.<CopyToAsyncInternal>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<PerformProxyRequest>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2017-08-02T17:07:53.0322180+03:00 0HL6PLT9ST49I [WRN] The response has already started, the error page middleware will not be executed. (e1dd4c0d)
2017-08-02T17:07:53.0461080+03:00 0HL6PLT9ST49I [ERR] Connection id ""0HL6PLT9JTA6C"": An unhandled exception was thrown by the application. (8c14976b)
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.IO.Stream.<CopyToAsyncInternal>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<PerformProxyRequest>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
2017-08-02T17:07:53.0634490+03:00 0HL6PLT9ST49I [INF] Request finished in 211635.2871ms 200 text/event-stream; charset=utf-8 (15c52c40)
2017-08-02T17:07:53.1262100+03:00 0HL6PLT9ST49J [WRN] User "db305aad-9be8-4116-8d23-436831384006" validation failed: "InvalidUserName". (5dc28e15)
2017-08-02T17:09:59.7770530+03:00 0HL6PM0KN0GL9 [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (e5be5b71)
2017-08-02T17:10:02.2630930+03:00 0HL6PM0KN0GL9 [INF] Executing action method "NXS.Controllers.HomeController.Index (NXS)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-02T17:10:12.1011130+03:00 0HL6PM0KN0GL9 [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2017-08-02T17:10:12.3732390+03:00 0HL6PM0KN0GL9 [INF] User profile is available. Using '"/Users/andriyarysmyatov/.aspnet/DataProtection-Keys"' as key repository; keys will not be encrypted at rest. (a162847e)
2017-08-02T17:10:16.1545910+03:00 0HL6PM0KN0GL9 [ERR] ERROR Error: jQuery requires a window with a document
    at module.exports.module.exports (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:19055:12)
    at HeaderComponent.ngAfterViewInit (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/main-server.js:13654:9)
    at callProviderLifecycles (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:15689:18)
    at callElementProvidersLifecycles (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:15664:13)
    at callLifecycleHooksChildrenFirst (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:15648:17)
    at checkAndUpdateView (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:16680:5)
    at callViewAction (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:17035:21)
    at execComponentViewsAction (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:16967:13)
    at Object.checkAndUpdateView (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:16678:5)
    at ViewRef_.module.exports.ViewRef_.detectChanges (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:14746:63) (34058d77)
2017-08-02T17:10:18.4341670+03:00 0HL6PM0KN0GLA [INF] Request starting HTTP/1.1 GET http://localhost:5000/__webpack_hmr   (e5be5b71)
2017-08-02T17:10:18.7383190+03:00 0HL6PM0KN0GLB [INF] Request starting HTTP/1.1 GET http://localhost:5000/__webpack_hmr   (e5be5b71)
2017-08-02T17:10:18.9312100+03:00 0HL6PM0KN0GLC [INF] Request starting HTTP/1.1 GET http://localhost:5000/__webpack_hmr   (e5be5b71)
2017-08-02T17:10:19.0824780+03:00 0HL6PM0KN0GLD [INF] Request starting HTTP/1.1 GET http://localhost:5000/dist/vendor.js?v=biT_xtz2y6Dm90XA962AZhAQ5b10hg1nNv_lMfkSrzQ   (e5be5b71)
2017-08-02T17:10:19.2840810+03:00 0HL6PM0KN0GLE [INF] Request starting HTTP/1.1 GET http://localhost:5000/dist/vendor.css?v=6V1XE9pBNVWZaG1AlsRZYfHMbu0miv3EsiQv-8jKmIg   (e5be5b71)
2017-08-02T17:10:19.4390580+03:00 0HL6PM0KN0GL9 [INF] Executed action "NXS.Controllers.HomeController.Index (NXS)" in 17313.9994ms (afa2e885)
2017-08-02T17:10:19.4914830+03:00 0HL6PM0KN0GL9 [INF] Request finished in 19965.0839ms 200 text/html; charset=utf-8 (15c52c40)
2017-08-02T17:10:19.5648540+03:00 0HL6PM0KN0GLF [INF] Request starting HTTP/1.1 GET http://localhost:5000/dist/main-client.js?v=gs9CuABfQKCtL-Q4LPfoQ4hbv3Rsz6MGH7oOziAIsAI   (e5be5b71)
2017-08-02T17:10:23.4151500+03:00 0HL6PM0KN0GLF [INF] Node will restart because file changed: /Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/main-server.js (23d2f42c)
2017-08-02T17:10:27.6578070+03:00  [INF] webpack built 58c21f0dd06b3b8bb7f9 in 30620ms (95f20a34)
2017-08-02T17:10:28.3607660+03:00 0HL6PM0KN0GLF [INF] Request finished in 8795.3307ms 200 application/javascript; charset=UTF-8 (15c52c40)
2017-08-02T17:10:28.3988460+03:00 0HL6PM0KN0GLD [INF] The file "/dist/vendor.js" was not modified (f1f8d725)
2017-08-02T17:10:28.3988720+03:00 0HL6PM0KN0GLE [INF] The file "/dist/vendor.css" was not modified (f1f8d725)
2017-08-02T17:10:28.4442660+03:00 0HL6PM0KN0GLE [INF] Request finished in 9159.7579ms 304 text/css (15c52c40)
2017-08-02T17:10:28.4443280+03:00 0HL6PM0KN0GLD [INF] Request finished in 9362.0675ms 304 application/javascript (15c52c40)
2017-08-02T17:10:31.6504480+03:00 0HL6PM0KN0GLG [INF] Request starting HTTP/1.1 GET http://localhost:5000/__webpack_hmr   (e5be5b71)
2017-08-02T17:10:31.7115860+03:00 0HL6PM0KN0GLH [INF] Request starting HTTP/1.1 GET http://localhost:5000/dist/6ebdb1f01dc905110782925239a570f8.jpg   (e5be5b71)
2017-08-02T17:10:31.8730790+03:00 0HL6PM0KN0GLH [INF] Request finished in 161.3904ms 200 image/jpeg; charset=UTF-8 (15c52c40)
2017-08-02T17:13:55.9678610+03:00 0HL6PM0KN0GLI [INF] Request starting HTTP/1.1 POST http://localhost:5000/api/account application/json 120 (e5be5b71)
2017-08-02T17:13:57.6344990+03:00 0HL6PM0KN0GLI [INF] Executing action method "NXS.Controllers.AccountController.Post (NXS)" with arguments (["NXS.Controllers.Resources.RegistrationInfoResource"]) - ModelState is Valid (ba7f4ac2)
2017-08-02T17:15:07.1647190+03:00 0HL6PM0KN0GLJ [INF] Request starting HTTP/1.1 GET http://localhost:5000/__webpack_hmr   (e5be5b71)
2017-08-02T17:15:07.3126480+03:00  [INF] Connection id ""0HL6PM0KAE950"" communication error. (7fa6c29c)
Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -32 EPIPE broken pipe
2017-08-02T17:15:07.3194150+03:00  [INF] Connection id ""0HL6PM0KAE950"" communication error. (7fa6c29c)
Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -32 EPIPE broken pipe
2017-08-02T17:15:07.3517240+03:00  [INF] Connection id ""0HL6PM0KAE950"" communication error. (7fa6c29c)
Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -32 EPIPE broken pipe
2017-08-02T17:15:08.2620940+03:00 0HL6PM0KN0GLI [INF] Executed action "NXS.Controllers.AccountController.Post (NXS)" in 72233.4592ms (afa2e885)
2017-08-02T17:15:08.5114140+03:00 0HL6PM0KN0GLI [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.InvalidOperationException: Cannot create a DbSet for 'NxsUser' because this type is not included in the model for the context.
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.FindByNameAsync(String normalizedUserName, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByNameAsync(String userName)
   at Microsoft.AspNetCore.Identity.UserValidator`1.<ValidateUserName>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Identity.UserValidator`1.<ValidateAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Identity.UserManager`1.<ValidateUserInternal>d__157.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Identity.UserManager`1.<CreateAsync>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Identity.UserManager`1.<CreateAsync>d__73.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NXS.Controllers.AccountController.<Post>d__4.MoveNext() in /Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/Controllers/AccountController.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2017-08-02T17:15:08.7069980+03:00 0HL6PM0KN0GLG [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.IO.Stream.<CopyToAsyncInternal>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<PerformProxyRequest>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2017-08-02T17:15:08.7177440+03:00 0HL6PM0KN0GLG [WRN] The response has already started, the error page middleware will not be executed. (e1dd4c0d)
2017-08-02T17:15:08.7506600+03:00 0HL6PM0KN0GLG [ERR] Connection id ""0HL6PM0KAE950"": An unhandled exception was thrown by the application. (8c14976b)
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.IO.Stream.<CopyToAsyncInternal>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<PerformProxyRequest>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
2017-08-02T17:15:08.7630780+03:00 0HL6PM0KN0GLG [INF] Request finished in 277099.9367ms 200 text/event-stream; charset=utf-8 (15c52c40)
2017-08-02T17:15:08.8131290+03:00 0HL6PM0KN0GLI [INF] Request finished in 72843.6393ms 500 text/html; charset=utf-8 (15c52c40)
2017-08-02T17:15:36.6940280+03:00 0HL6PM0KN0GLK [INF] Request starting HTTP/1.1 POST http://localhost:5000/api/account application/json 120 (e5be5b71)
2017-08-02T17:15:36.7380280+03:00 0HL6PM0KN0GLK [INF] Executing action method "NXS.Controllers.AccountController.Post (NXS)" with arguments (["NXS.Controllers.Resources.RegistrationInfoResource"]) - ModelState is Valid (ba7f4ac2)
2017-08-02T17:16:59.8009610+03:00 0HL6PM0KN0GLK [INF] Executed action "NXS.Controllers.AccountController.Post (NXS)" in 83065.0303ms (afa2e885)
2017-08-02T17:16:59.8262910+03:00 0HL6PM0KN0GLK [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.InvalidOperationException: Cannot create a DbSet for 'NxsUser' because this type is not included in the model for the context.
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.FindByNameAsync(String normalizedUserName, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByNameAsync(String userName)
   at Microsoft.AspNetCore.Identity.UserValidator`1.<ValidateUserName>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Identity.UserValidator`1.<ValidateAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Identity.UserManager`1.<ValidateUserInternal>d__157.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Identity.UserManager`1.<CreateAsync>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Identity.UserManager`1.<CreateAsync>d__73.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NXS.Controllers.AccountController.<Post>d__4.MoveNext() in /Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/Controllers/AccountController.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2017-08-02T17:16:59.8875120+03:00 0HL6PM0KN0GLK [INF] Request finished in 83189.6979ms 500 text/html; charset=utf-8 (15c52c40)
2017-08-02T17:20:46.0875800+03:00 0HL6PM6L9U6OB [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (e5be5b71)
2017-08-02T17:20:48.1103910+03:00 0HL6PM6L9U6OB [INF] Executing action method "NXS.Controllers.HomeController.Index (NXS)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-02T17:20:57.0447620+03:00 0HL6PM6L9U6OB [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2017-08-02T17:20:57.4208320+03:00 0HL6PM6L9U6OB [INF] User profile is available. Using '"/Users/andriyarysmyatov/.aspnet/DataProtection-Keys"' as key repository; keys will not be encrypted at rest. (a162847e)
2017-08-02T17:21:00.6374140+03:00 0HL6PM6L9U6OB [ERR] ERROR Error: jQuery requires a window with a document
    at module.exports.module.exports (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:19055:12)
    at HeaderComponent.ngAfterViewInit (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/main-server.js:13654:9)
    at callProviderLifecycles (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:15689:18)
    at callElementProvidersLifecycles (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:15664:13)
    at callLifecycleHooksChildrenFirst (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:15648:17)
    at checkAndUpdateView (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:16680:5)
    at callViewAction (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:17035:21)
    at execComponentViewsAction (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:16967:13)
    at Object.checkAndUpdateView (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:16678:5)
    at ViewRef_.module.exports.ViewRef_.detectChanges (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:14746:63) (34058d77)
2017-08-02T17:21:01.6660500+03:00 0HL6PM6L9U6OB [INF] Executed action "NXS.Controllers.HomeController.Index (NXS)" in 14050.9603ms (afa2e885)
2017-08-02T17:21:01.7693980+03:00 0HL6PM6L9U6OB [INF] Request finished in 15770.0246ms 200 text/html; charset=utf-8 (15c52c40)
2017-08-02T17:21:02.4071280+03:00 0HL6PM6L9U6OC [INF] Request starting HTTP/1.1 GET http://localhost:5000/__webpack_hmr   (e5be5b71)
2017-08-02T17:21:02.4253400+03:00 0HL6PM6L9U6OD [INF] Request starting HTTP/1.1 GET http://localhost:5000/dist/vendor.css?v=6V1XE9pBNVWZaG1AlsRZYfHMbu0miv3EsiQv-8jKmIg   (e5be5b71)
2017-08-02T17:21:02.4540580+03:00 0HL6PM6L9U6OE [INF] Request starting HTTP/1.1 GET http://localhost:5000/dist/vendor.js?v=biT_xtz2y6Dm90XA962AZhAQ5b10hg1nNv_lMfkSrzQ   (e5be5b71)
2017-08-02T17:21:02.7181330+03:00 0HL6PM6L9U6OF [INF] Request starting HTTP/1.1 GET http://localhost:5000/dist/main-client.js?v=gs9CuABfQKCtL-Q4LPfoQ4hbv3Rsz6MGH7oOziAIsAI   (e5be5b71)
2017-08-02T17:21:04.0997160+03:00 0HL6PM6L9U6OE [INF] Node will restart because file changed: /Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/main-server.js (23d2f42c)
2017-08-02T17:21:06.6195310+03:00  [INF] webpack built 58c21f0dd06b3b8bb7f9 in 22787ms (b2783944)
2017-08-02T17:21:07.0266220+03:00 0HL6PM6L9U6OD [INF] The file "/dist/vendor.css" was not modified (f1f8d725)
2017-08-02T17:21:07.0321230+03:00 0HL6PM6L9U6OE [INF] The file "/dist/vendor.js" was not modified (f1f8d725)
2017-08-02T17:21:07.0791300+03:00 0HL6PM6L9U6OF [INF] Request finished in 4360.7586ms 200 application/javascript; charset=UTF-8 (15c52c40)
2017-08-02T17:21:07.0935190+03:00 0HL6PM6L9U6OD [INF] Request finished in 4668.0406ms 304 text/css (15c52c40)
2017-08-02T17:21:07.3534750+03:00 0HL6PM6L9U6OE [INF] Request finished in 4899.2787ms 304 application/javascript (15c52c40)
2017-08-02T17:21:09.8532910+03:00 0HL6PM6L9U6OG [INF] Request starting HTTP/1.1 GET http://localhost:5000/__webpack_hmr   (e5be5b71)
2017-08-02T17:21:09.9017180+03:00 0HL6PM6L9U6OH [INF] Request starting HTTP/1.1 GET http://localhost:5000/dist/6ebdb1f01dc905110782925239a570f8.jpg   (e5be5b71)
2017-08-02T17:21:10.0695470+03:00 0HL6PM6L9U6OH [INF] Request finished in 167.8359ms 200 image/jpeg; charset=UTF-8 (15c52c40)
2017-08-02T17:21:33.0853780+03:00 0HL6PM6L9U6OI [INF] Request starting HTTP/1.1 POST http://localhost:5000/api/account application/json 120 (e5be5b71)
2017-08-02T17:21:33.7326150+03:00 0HL6PM6L9U6OI [INF] Executing action method "NXS.Controllers.AccountController.Post (NXS)" with arguments (["NXS.Controllers.Resources.RegistrationInfoResource"]) - ModelState is Valid (ba7f4ac2)
2017-08-02T17:21:44.2710300+03:00 0HL6PM6L9U6OI [INF] Executed DbCommand (230ms) [Parameters=[@__normalizedUserName_0='?' (Size = 256)], CommandType='Text', CommandTimeout='30']
SELECT TOP(1) [u].[Id], [u].[AccessFailedCount], [u].[ConcurrencyStamp], [u].[Email], [u].[EmailConfirmed], [u].[FirstName], [u].[LastName], [u].[LockoutEnabled], [u].[LockoutEnd], [u].[NormalizedEmail], [u].[NormalizedUserName], [u].[PasswordHash], [u].[PhoneNumber], [u].[PhoneNumberConfirmed], [u].[SecurityStamp], [u].[TwoFactorEnabled], [u].[UserName]
FROM [AspNetUsers] AS [u]
WHERE [u].[NormalizedUserName] = @__normalizedUserName_0 (6438bdd5)
2017-08-02T17:21:44.5546040+03:00 0HL6PM6L9U6OI [ERR] An exception occurred in the database while iterating the results of a query.
 (3b5ca34b)
System.Data.SqlClient.SqlException: Invalid column name 'FirstName'.
Invalid column name 'LastName'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__107_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable.AsyncEnumerator.<BufferlessMoveNext>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__6`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable.AsyncEnumerator.<MoveNext>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.SelectAsyncEnumerable`2.SelectAsyncEnumerator.<MoveNext>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.<_FirstOrDefault>d__82`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.TaskResultAsyncEnumerable`1.Enumerator.<MoveNext>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.SelectAsyncEnumerable`2.SelectAsyncEnumerator.<MoveNext>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
ClientConnectionId:df222fff-29db-4f8a-a9dc-48c028656605
Error Number:207,State:1,Class:16
2017-08-02T17:21:45.3817210+03:00 0HL6PM6L9U6OI [INF] Executed action "NXS.Controllers.AccountController.Post (NXS)" in 12264.4874ms (afa2e885)
2017-08-02T17:21:45.4092870+03:00 0HL6PM6L9U6OI [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.Data.SqlClient.SqlException: Invalid column name 'FirstName'.
Invalid column name 'LastName'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__107_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable.AsyncEnumerator.<BufferlessMoveNext>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__6`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable.AsyncEnumerator.<MoveNext>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.SelectAsyncEnumerable`2.SelectAsyncEnumerator.<MoveNext>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.<_FirstOrDefault>d__82`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.TaskResultAsyncEnumerable`1.Enumerator.<MoveNext>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.SelectAsyncEnumerable`2.SelectAsyncEnumerator.<MoveNext>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Identity.UserValidator`1.<ValidateUserName>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Identity.UserValidator`1.<ValidateAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Identity.UserManager`1.<ValidateUserInternal>d__157.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Identity.UserManager`1.<CreateAsync>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Identity.UserManager`1.<CreateAsync>d__73.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NXS.Controllers.AccountController.<Post>d__4.MoveNext() in /Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/Controllers/AccountController.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
ClientConnectionId:df222fff-29db-4f8a-a9dc-48c028656605
Error Number:207,State:1,Class:16
2017-08-02T17:21:45.7608670+03:00 0HL6PM6L9U6OI [INF] Request finished in 12674.5895ms 500 text/html; charset=utf-8 (15c52c40)
2017-08-02T17:26:45.8514310+03:00 0HL6PMA0GV8DV [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (e5be5b71)
2017-08-02T17:26:48.1781610+03:00 0HL6PMA0GV8DV [INF] Executing action method "NXS.Controllers.HomeController.Index (NXS)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-02T17:26:55.4936970+03:00 0HL6PMA0GV8DV [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2017-08-02T17:26:55.8420010+03:00 0HL6PMA0GV8DV [INF] User profile is available. Using '"/Users/andriyarysmyatov/.aspnet/DataProtection-Keys"' as key repository; keys will not be encrypted at rest. (a162847e)
2017-08-02T17:26:59.3670880+03:00 0HL6PMA0GV8DV [ERR] ERROR Error: jQuery requires a window with a document
    at module.exports.module.exports (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:19055:12)
    at HeaderComponent.ngAfterViewInit (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/main-server.js:13654:9)
    at callProviderLifecycles (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:15689:18)
    at callElementProvidersLifecycles (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:15664:13)
    at callLifecycleHooksChildrenFirst (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:15648:17)
    at checkAndUpdateView (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:16680:5)
    at callViewAction (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:17035:21)
    at execComponentViewsAction (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:16967:13)
    at Object.checkAndUpdateView (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:16678:5)
    at ViewRef_.module.exports.ViewRef_.detectChanges (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:14746:63) (34058d77)
2017-08-02T17:27:00.7710400+03:00 0HL6PMA0GV8DV [INF] Executed action "NXS.Controllers.HomeController.Index (NXS)" in 12964.0956ms (afa2e885)
2017-08-02T17:27:00.9777500+03:00 0HL6PMA0GV8DV [INF] Request finished in 15214.5898ms 200 text/html; charset=utf-8 (15c52c40)
2017-08-02T17:27:01.1204690+03:00 0HL6PMA0GV8E0 [INF] Request starting HTTP/1.1 GET http://localhost:5000/__webpack_hmr   (e5be5b71)
2017-08-02T17:27:01.3397040+03:00 0HL6PMA0GV8E1 [INF] Request starting HTTP/1.1 GET http://localhost:5000/dist/main-client.js?v=gs9CuABfQKCtL-Q4LPfoQ4hbv3Rsz6MGH7oOziAIsAI   (e5be5b71)
2017-08-02T17:27:03.7470630+03:00 0HL6PMA0GV8E0 [INF] Node will restart because file changed: /Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/main-server.js (23d2f42c)
2017-08-02T17:27:05.7615100+03:00  [INF] webpack built 58c21f0dd06b3b8bb7f9 in 22569ms (c7b1f1e5)
2017-08-02T17:27:06.1451470+03:00 0HL6PMA0GV8E1 [INF] Request finished in 4805.1689ms 200 application/javascript; charset=UTF-8 (15c52c40)
2017-08-02T17:27:08.3921290+03:00 0HL6PMA0GV8E2 [INF] Request starting HTTP/1.1 GET http://localhost:5000/dist/6ebdb1f01dc905110782925239a570f8.jpg   (e5be5b71)
2017-08-02T17:27:08.4567600+03:00 0HL6PMA0GV8E3 [INF] Request starting HTTP/1.1 GET http://localhost:5000/__webpack_hmr   (e5be5b71)
2017-08-02T17:27:08.8906780+03:00 0HL6PMA0GV8E2 [INF] Request finished in 498.5571ms 200 image/jpeg; charset=UTF-8 (15c52c40)
2017-08-02T17:27:42.6087810+03:00 0HL6PMA0GV8E4 [INF] Request starting HTTP/1.1 POST http://localhost:5000/api/account application/json 120 (e5be5b71)
2017-08-02T17:27:43.5716630+03:00 0HL6PMA0GV8E4 [INF] Executing action method "NXS.Controllers.AccountController.Post (NXS)" with arguments (["NXS.Controllers.Resources.RegistrationInfoResource"]) - ModelState is Valid (ba7f4ac2)
2017-08-02T17:27:53.8032480+03:00 0HL6PMA0GV8E4 [INF] Executed DbCommand (239ms) [Parameters=[@__normalizedUserName_0='?' (Size = 256)], CommandType='Text', CommandTimeout='30']
SELECT TOP(1) [u].[Id], [u].[AccessFailedCount], [u].[ConcurrencyStamp], [u].[Email], [u].[EmailConfirmed], [u].[FirstName], [u].[LastName], [u].[LockoutEnabled], [u].[LockoutEnd], [u].[NormalizedEmail], [u].[NormalizedUserName], [u].[PasswordHash], [u].[PhoneNumber], [u].[PhoneNumberConfirmed], [u].[SecurityStamp], [u].[TwoFactorEnabled], [u].[UserName]
FROM [AspNetUsers] AS [u]
WHERE [u].[NormalizedUserName] = @__normalizedUserName_0 (6438bdd5)
2017-08-02T17:27:54.4809070+03:00 0HL6PMA0GV8E4 [INF] Executed DbCommand (105ms) [Parameters=[@p0='?' (Size = 450), @p1='?', @p2='?' (Size = 4000), @p3='?' (Size = 256), @p4='?', @p5='?' (Size = 4000), @p6='?' (Size = 4000), @p7='?', @p8='?', @p9='?' (Size = 256), @p10='?' (Size = 256), @p11='?' (Size = 4000), @p12='?' (Size = 4000), @p13='?', @p14='?' (Size = 4000), @p15='?', @p16='?' (Size = 256)], CommandType='Text', CommandTimeout='30']
SET NOCOUNT ON;
INSERT INTO [AspNetUsers] ([Id], [AccessFailedCount], [ConcurrencyStamp], [Email], [EmailConfirmed], [FirstName], [LastName], [LockoutEnabled], [LockoutEnd], [NormalizedEmail], [NormalizedUserName], [PasswordHash], [PhoneNumber], [PhoneNumberConfirmed], [SecurityStamp], [TwoFactorEnabled], [UserName])
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14, @p15, @p16); (6438bdd5)
2017-08-02T17:27:59.4046710+03:00 0HL6PMA0GV8E4 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2017-08-02T17:27:59.4234870+03:00 0HL6PMA0GV8E4 [INF] Executed action "NXS.Controllers.AccountController.Post (NXS)" in 16759.1131ms (afa2e885)
2017-08-02T17:27:59.4328330+03:00 0HL6PMA0GV8E4 [INF] Request finished in 16824.0905ms 200 text/plain; charset=utf-8 (15c52c40)
2017-08-02T18:10:31.3748190+03:00 0HL6PN2EVR40L [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (e5be5b71)
2017-08-02T18:10:32.4876430+03:00 0HL6PN2EVR40L [INF] Executing action method "NXS.Controllers.HomeController.Index (NXS)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-02T18:10:42.2220940+03:00 0HL6PN2EVR40L [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2017-08-02T18:10:42.5574610+03:00 0HL6PN2EVR40L [INF] User profile is available. Using '"/Users/andriyarysmyatov/.aspnet/DataProtection-Keys"' as key repository; keys will not be encrypted at rest. (a162847e)
2017-08-02T18:10:47.4241550+03:00 0HL6PN2EVR40L [ERR] ERROR Error: jQuery requires a window with a document
    at module.exports.module.exports (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:19055:12)
    at HeaderComponent.ngAfterViewInit (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/main-server.js:13654:9)
    at callProviderLifecycles (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:15689:18)
    at callElementProvidersLifecycles (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:15664:13)
    at callLifecycleHooksChildrenFirst (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:15648:17)
    at checkAndUpdateView (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:16680:5)
    at callViewAction (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:17035:21)
    at execComponentViewsAction (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:16967:13)
    at Object.checkAndUpdateView (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:16678:5)
    at ViewRef_.module.exports.ViewRef_.detectChanges (/Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/vendor.js:14746:63) (34058d77)
2017-08-02T18:10:49.0104530+03:00 0HL6PN2EVR40M [INF] Request starting HTTP/1.1 GET http://localhost:5000/dist/vendor.css?v=6V1XE9pBNVWZaG1AlsRZYfHMbu0miv3EsiQv-8jKmIg   (e5be5b71)
2017-08-02T18:10:49.1998100+03:00 0HL6PN2EVR40L [INF] Executed action "NXS.Controllers.HomeController.Index (NXS)" in 16904.2202ms (afa2e885)
2017-08-02T18:10:49.2987630+03:00 0HL6PN2EVR40L [INF] Request finished in 17999.8837ms 200 text/html; charset=utf-8 (15c52c40)
2017-08-02T18:10:49.6644030+03:00 0HL6PN2EVR40N [INF] Request starting HTTP/1.1 GET http://localhost:5000/dist/main-client.js?v=gs9CuABfQKCtL-Q4LPfoQ4hbv3Rsz6MGH7oOziAIsAI   (e5be5b71)
2017-08-02T18:10:49.6644240+03:00 0HL6PN2EVR40O [INF] Request starting HTTP/1.1 GET http://localhost:5000/dist/vendor.js?v=biT_xtz2y6Dm90XA962AZhAQ5b10hg1nNv_lMfkSrzQ   (e5be5b71)
2017-08-02T18:10:53.4804660+03:00 0HL6PN2EVR40N [INF] Node will restart because file changed: /Users/andriyarysmyatov/Documents/Documents - Andriy’s MacBook Pro/Work/theresourcenexus/project_0_3/NXS/ClientApp/dist/main-server.js (23d2f42c)
2017-08-02T18:10:56.9385910+03:00  [INF] webpack built 58c21f0dd06b3b8bb7f9 in 27635ms (35d3f3d8)
2017-08-02T18:10:57.3845120+03:00 0HL6PN2EVR40N [INF] Request finished in 7719.6939ms 200 application/javascript; charset=UTF-8 (15c52c40)
2017-08-02T18:10:57.4006150+03:00 0HL6PN2EVR40M [INF] The file "/dist/vendor.css" was not modified (f1f8d725)
2017-08-02T18:10:57.4006320+03:00 0HL6PN2EVR40O [INF] The file "/dist/vendor.js" was not modified (f1f8d725)
2017-08-02T18:10:57.4431540+03:00 0HL6PN2EVR40O [INF] Request finished in 7778.3883ms 304 application/javascript (15c52c40)
2017-08-02T18:10:57.5055040+03:00 0HL6PN2EVR40M [INF] Request finished in 8432.8118ms 304 text/css (15c52c40)
2017-08-02T18:11:02.9277940+03:00 0HL6PN2EVR40P [INF] Request starting HTTP/1.1 GET http://localhost:5000/__webpack_hmr   (e5be5b71)
2017-08-02T18:11:02.9900800+03:00 0HL6PN2EVR40Q [INF] Request starting HTTP/1.1 GET http://localhost:5000/dist/6ebdb1f01dc905110782925239a570f8.jpg   (e5be5b71)
2017-08-02T18:11:03.4226660+03:00 0HL6PN2EVR40Q [INF] Request finished in 426.0828ms 200 image/jpeg; charset=UTF-8 (15c52c40)
2017-08-02T18:16:49.2407140+03:00 0HL6PN2EVR40R [INF] Request starting HTTP/1.1 POST http://localhost:5000/api/auth/login application/json 68 (e5be5b71)
2017-08-02T18:16:49.8645860+03:00 0HL6PN2EVR40R [INF] Executing action method "NXS.Controllers.AuthController.Post (NXS)" with arguments (["CredentialsResource"]) - ModelState is Valid (ba7f4ac2)
2017-08-02T18:17:02.1796570+03:00 0HL6PN2EVR40R [INF] Executed DbCommand (408ms) [Parameters=[@__normalizedUserName_0='?' (Size = 256)], CommandType='Text', CommandTimeout='30']
SELECT TOP(1) [u].[Id], [u].[AccessFailedCount], [u].[ConcurrencyStamp], [u].[Email], [u].[EmailConfirmed], [u].[FirstName], [u].[LastName], [u].[LockoutEnabled], [u].[LockoutEnd], [u].[NormalizedEmail], [u].[NormalizedUserName], [u].[PasswordHash], [u].[PhoneNumber], [u].[PhoneNumberConfirmed], [u].[SecurityStamp], [u].[TwoFactorEnabled], [u].[UserName]
FROM [AspNetUsers] AS [u]
WHERE [u].[NormalizedUserName] = @__normalizedUserName_0 (6438bdd5)
2017-08-02T18:17:16.8804230+03:00 0HL6PN2EVR40R [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2017-08-02T18:17:16.8947840+03:00 0HL6PN2EVR40R [INF] Executed action "NXS.Controllers.AuthController.Post (NXS)" in 27604.8184ms (afa2e885)
2017-08-02T18:17:16.9050690+03:00 0HL6PN2EVR40R [INF] Request finished in 27664.7983ms 200 text/plain; charset=utf-8 (15c52c40)
